### ISSUE TITLE
Shutdown after a fixed number of reconnection attempts

### ISSUE THREAD

**Issue by abbasegbeyemi** [wagslane/go-rabbitmq#139]
I want to be able to shut down the consumer/publisher gouroutines and by extension the entire app after a few attempts at reconnecting to the rabbitmq server. Is there a way to implement this with this library?

I can see that the `ChannelManager` and `ConnectionManager` both increment reconnection count, is there a way to use this value to determine when the managers should give up trying to reconnect?

**Comment by wagslane** [comment]
If you want that kind of granular control I think the base amqp lib is for you

**Comment by yagnasrinath** [comment]
@wagslane This is a great library and provides a lot of good functionality that the official library itself doesn't care to provide.
Having said that we have recently run into an issue where the library continuous to reconnect unsuccessfully, even though it could never establish a connection to the server. This can result in silent failures. Lot of times the cloud services depend on the application restart/fail fast approach to alert the operator that there is something wrong. It would be great to have an ability to limit the number of reconnections attempted and the default could be unlimited like it is now. It would really help our usecases to fail fast.
At the same time, we were seeing an issue where the dial is running into an exception(`Exception (501) Reason: \" remote error: tls: expired certificate\"`) and possibly incorrectly saying that the server certificate has expired. Although neither server nor client cert expired. But when we restart the application, the client was able to successfully establish the connection immediately. Since it is our production environment, we couldn't enable any debug logging. 

Limiting number of reconnections will be useful and can give a temporary solutions for applications to get past the unforeseen errors, that library could never recover from.
